#ifndef CARRYHANDLE_CH_CARD_PRESENTATION_H
#define CARRYHANDLE_CH_CARD_PRESENTATION_H

#include <stdbool.h>

#include <ogc/card.h>

#ifdef __cplusplus
extern "C" {
#endif


/*
 * Size of the CI8 CARD presentation format currently generated by
 * CarryHandle:
 *
 *   3072 bytes  banner CI8
 *    512 bytes  banner RGB5A3 TLUT
 *   1024 bytes  icon CI8
 *    512 bytes  icon RGB5A3 TLUT
 *     64 bytes  two CARD comment lines
 */
#define CH_CARD_PRESENTATION_CI8_SIZE 5184u


/*
 * Install GameCube Memory Card presentation data into an already-open
 * CARD file.
 *
 * file:
 *     An open libogc2 card_file belonging to a mounted Memory Card.
 *
 * sector_size:
 *     The physical CARD sector size used for CARD_Read/CARD_Write.
 *
 * sector_buffer:
 *     Caller-owned scratch space of at least sector_size bytes.
 *     It must be 32-byte aligned.
 *
 * presentation_offset:
 *     Byte offset within sector zero at which the generated 5184-byte
 *     presentation blob is stored.
 *
 *     It must be less than CARD_READSIZE because libogc2's icon_addr
 *     uses this value as the base from which banner/icon offsets are
 *     derived.
 *
 * presentation_data:
 *     The generated CI8/RGB5A3 presentation blob.
 *
 * presentation_size:
 *     Must currently equal CH_CARD_PRESENTATION_CI8_SIZE.
 *
 * The function first reads sector zero and preserves every byte outside
 * the presentation range. It is therefore suitable for storage formats
 * that reserve some sector-zero space for their own headers.
 *
 * The operation is idempotent: if both payload and CARD directory
 * metadata are already correct, no write is performed.
 *
 * CarryHandle assigns no persistence-validity meaning to presentation
 * success or failure. Applications/storage modules must decide whether
 * a cosmetic presentation failure matters to them.
 */
bool CH_CardPresentationApply(
    card_file *file,
    s32 sector_size,
    void *sector_buffer,
    u32 presentation_offset,
    const unsigned char *presentation_data,
    u32 presentation_size
);


#ifdef __cplusplus
}
#endif

#endif
