# -----------------------------------------------------------------------------
# CarryHandle reusable GameCube application build scaffold.
#
# Consumer owns:
#   - application source inventory
#   - application-specific compiler/linker policy through APP_*
#   - game-specific disc staging
#   - application-specific test/release policy
#
# CarryHandle owns:
#   - devkitPPC/libogc2 toolchain setup
#   - common compiler/linker mechanics
#   - outer/inner build recursion
#   - selected CarryHandle module integration
#   - common clean/run mechanics
#   - DEBUG/TRACE hooks
# -----------------------------------------------------------------------------

.SUFFIXES:
.DEFAULT_GOAL := all


# -----------------------------------------------------------------------------
# Toolchain
# -----------------------------------------------------------------------------

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment.")
endif

ifeq ($(strip $(DEVKITPPC)),)
$(error "Please set DEVKITPPC in your environment.")
endif

ifndef PROJECT_DIR
$(error "Consumer must define PROJECT_DIR before including gamecube.mk")
endif

CARRY_ROOT ?= $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/..)

# The first makefile is the consumer, even after gamecube_rules and shared
# fragments append themselves to MAKEFILE_LIST.
CONSUMER_MAKEFILE := $(abspath $(firstword $(MAKEFILE_LIST)))

include $(DEVKITPRO)/libogc2/gamecube_rules


# -----------------------------------------------------------------------------
# Standard application interface
# -----------------------------------------------------------------------------

TARGET ?= app
BUILD  ?= build

DEBUG ?= 1
TRACE ?= 0

APP_OPTFLAGS ?= -O2
APP_WARNINGS ?= -Wall

APP_CFLAGS       ?=
APP_CXXFLAGS     ?=
APP_DEBUG_CFLAGS ?=
APP_TRACE_CFLAGS ?=
APP_LDFLAGS      ?=

APP_LIBS ?= \
	-logc \
	-lm

APP_INCLUDES ?=
APP_LIBDIRS  ?=


# -----------------------------------------------------------------------------
# CarryHandle modules
# -----------------------------------------------------------------------------

CH_CFILES ?=

CH_SOURCE_DIRS ?= \
	$(CARRY_ROOT)/source \
	$(CARRY_ROOT)/source/video

ifneq ($(strip $(CH_CFILES)),)

SOURCES += \
	$(CH_SOURCE_DIRS)

CFILES += \
	$(CH_CFILES)

# CH_DVD_REQUIRES_FAT
# Swiss-launched image backing uses the libfat-compatible API supplied by
# libogc2-libfat or libogc2-libdvm.
ifneq ($(filter ch_dvd.c,$(CH_CFILES)),)
APP_LIBS := -lfat $(APP_LIBS)

# CH_DVD_REMOTE_DISC_DEPENDENCY
# ch_dvd.c exposes optional PC-hosted dvd:/ backing through the generic
# remote-disc transport. Pull the transport implementation in automatically
# so existing consumers selecting ch_dvd.c do not acquire another required
# CH_CFILES entry.
ifeq ($(filter ch_remote_disc.c,$(CH_CFILES)),)
CFILES += ch_remote_disc.c
endif

endif

# Consumers select modules; CarryHandle owns where its public headers live.
APP_INCLUDES += \
	$(CARRY_ROOT)/include

endif


# -----------------------------------------------------------------------------
# Compiler / linker policy generated by CarryHandle
# -----------------------------------------------------------------------------

CFLAGS = \
	-g \
	$(APP_OPTFLAGS) \
	$(APP_WARNINGS) \
	$(MACHDEP) \
	$(INCLUDE) \
	$(APP_CFLAGS)

CXXFLAGS = \
	$(CFLAGS) \
	$(APP_CXXFLAGS)

LDFLAGS = \
	-g \
	$(MACHDEP) \
	-Wl,-Map,$(notdir $@).map \
	$(APP_LDFLAGS)

LIBS = \
	$(APP_LIBS)

ifeq ($(DEBUG),1)
CFLAGS += \
	$(APP_DEBUG_CFLAGS)
endif

ifeq ($(TRACE),1)
CFLAGS += \
	$(APP_TRACE_CFLAGS)
endif


# -----------------------------------------------------------------------------
# Default parallelism
# -----------------------------------------------------------------------------

CH_JOBS ?= \
	$(shell getconf _NPROCESSORS_ONLN 2>/dev/null || nproc 2>/dev/null || echo 1)

CH_MAKE_JOB_FLAGS := \
	$(filter -j% j% --jobs% --jobserver-auth=% --jobserver-fds=%,$(MAKEFLAGS))

ifeq ($(strip $(CH_MAKE_JOB_FLAGS)),)
MAKEFLAGS += -j$(CH_JOBS)
endif


# -----------------------------------------------------------------------------
# Common run / clean policy
# -----------------------------------------------------------------------------

RUNNER ?= wiiload
RUNNER_ARGS ?=
RUN_IMAGE ?= $(PROJECT_DIR)/$(TARGET).dol

# wiiload uses WIILOAD to select its transport destination.
#
# Preserve an explicit environment/command-line WIILOAD value. Otherwise,
# automatically select a single USB Gecko exposed through Linux's stable
# /dev/serial/by-id namespace.
CH_USB_GECKO_DEVICES := $(wildcard /dev/serial/by-id/*USB*Gecko*)
WIILOAD ?= $(if $(filter 1,$(words $(CH_USB_GECKO_DEVICES))),$(firstword $(CH_USB_GECKO_DEVICES)))
CH_RUNNER_NAME := $(notdir $(firstword $(RUNNER)))

# PC-hosted GameCube image development transport.
#
# run-remote intentionally remains distinct from run:
#
#   make run
#       upload/launch the DOL only
#
#   make run-remote REMOTE_IMAGE=/path/to/game.iso
#       upload/launch the DOL, then serve that image over USB Gecko
#
# REMOTE_DEVICE defaults to the same stable USB Gecko selected for wiiload.
REMOTE_IMAGE ?=
REMOTE_DEVICE ?= $(WIILOAD)
REMOTE_SERVER ?= $(CARRY_ROOT)/tools/remote-disc/ch_remote_disc_server.py
REMOTE_PYTHON ?= python3
REMOTE_SERVER_ARGS ?=
REMOTE_SERVER_DELAY ?= 0.10

CLEAN_FILES ?=
CLEAN_DIRS ?=


# -----------------------------------------------------------------------------
# Include policy
# -----------------------------------------------------------------------------
#
# Compute this in both the outer and recursive child invocation. Consumers may
# have legacy INCLUDE assignments earlier in their Makefiles; CarryHandle owns
# the final include set for the scaffold and must reassert it after inclusion.
#
export INCLUDE := \
	$(foreach dir,$(APP_INCLUDES),-I$(dir)) \
	-I$(PROJECT_DIR) \
	-I$(PROJECT_DIR)/$(BUILD) \
	-I$(LIBOGC_INC)


# -----------------------------------------------------------------------------
# Outer build
# -----------------------------------------------------------------------------

ifneq ($(BUILD),$(notdir $(CURDIR)))

export OUTPUT := \
	$(PROJECT_DIR)/$(TARGET)

export DEPSDIR := \
	$(PROJECT_DIR)/$(BUILD)

export VPATH := \
	$(SOURCES)

CPPFILES ?=
sFILES   ?=
SFILES   ?=

export LIBPATHS := \
	$(foreach dir,$(APP_LIBDIRS),-L$(dir)/lib) \
	-L$(LIBOGC_LIB)

export LD := \
	$(if $(strip $(CPPFILES)),$(CXX),$(CC))

export OFILES := \
	$(CPPFILES:.cpp=.o) \
	$(CFILES:.c=.o) \
	$(sFILES:.s=.o) \
	$(SFILES:.S=.o)


.PHONY: \
	all \
	$(BUILD) \
	clean \
	run \
	run-remote

all: $(BUILD)

$(BUILD):
	@mkdir -p "$(PROJECT_DIR)/$(BUILD)"
	@$(MAKE) \
		--no-print-directory \
		-C "$(PROJECT_DIR)/$(BUILD)" \
		-f "$(CONSUMER_MAKEFILE)" \
		"$(PROJECT_DIR)/$(TARGET).dol"

clean:
	@echo clean ...
	@rm -rf \
		"$(PROJECT_DIR)/$(BUILD)" \
		"$(PROJECT_DIR)/$(TARGET).elf" \
		"$(PROJECT_DIR)/$(TARGET).dol" \
		"$(PROJECT_DIR)/$(TARGET).elf.map" \
		$(CLEAN_FILES) \
		$(CLEAN_DIRS)

run: all
	@test -f "$(RUN_IMAGE)" || \
		( echo "ERROR: missing run image $(RUN_IMAGE)"; false )
ifeq ($(CH_RUNNER_NAME),wiiload)
	@test -n "$(strip $(WIILOAD))" || { \
		count="$(words $(CH_USB_GECKO_DEVICES))"; \
		if [ "$$count" -gt 1 ]; then \
			echo "ERROR: multiple USB Gecko devices found; set WIILOAD explicitly"; \
		else \
			echo "ERROR: no USB Gecko found under /dev/serial/by-id"; \
			echo "       set WIILOAD explicitly to override auto-discovery"; \
		fi; \
		false; \
	}
	@case "$(WIILOAD)" in \
		/*) \
			test -r "$(WIILOAD)" && test -w "$(WIILOAD)" || { \
				echo "ERROR: wiiload device is not readable/writable: $(WIILOAD)"; \
				echo "       check device permissions / dialout membership"; \
				false; \
			} ;; \
		*) : ;; \
	esac
	@echo "USB Gecko: $(WIILOAD)"
	WIILOAD="$(WIILOAD)" \
		$(RUNNER) \
		$(RUNNER_ARGS) \
		"$(RUN_IMAGE)"
else
	$(RUNNER) \
		$(RUNNER_ARGS) \
		"$(RUN_IMAGE)"
endif



# -----------------------------------------------------------------------------
# PC-hosted remote-disc development run
# -----------------------------------------------------------------------------

run-remote: all
	@test -n "$(strip $(REMOTE_IMAGE))" || { \
		echo "ERROR: run-remote requires REMOTE_IMAGE=/path/to/game.iso"; \
		false; \
	}
	@test -f "$(REMOTE_IMAGE)" || { \
		echo "ERROR: remote image not found: $(REMOTE_IMAGE)"; \
		false; \
	}
	@test -f "$(REMOTE_SERVER)" || { \
		echo "ERROR: CarryHandle remote-disc server missing: $(REMOTE_SERVER)"; \
		false; \
	}
	@test -n "$(strip $(REMOTE_DEVICE))" || { \
		echo "ERROR: no USB Gecko selected for remote-disc transport"; \
		echo "       set REMOTE_DEVICE=/dev/serial/by-id/... explicitly"; \
		false; \
	}
	@case "$(REMOTE_DEVICE)" in \
		/*) : ;; \
		*) \
			echo "ERROR: REMOTE_DEVICE must be a local serial-device path"; \
			echo "       got: $(REMOTE_DEVICE)"; \
			false ;; \
	esac
	@echo "Remote image : $(REMOTE_IMAGE)"
	@echo "Remote Gecko : $(REMOTE_DEVICE)"
	@echo
	@$(MAKE) \
		--no-print-directory \
		-f "$(CONSUMER_MAKEFILE)" \
		WIILOAD="$(REMOTE_DEVICE)" \
		run
	@sleep "$(REMOTE_SERVER_DELAY)"
	@echo
	@echo "Starting CarryHandle remote-disc server..."
	@echo
	$(REMOTE_PYTHON) \
		"$(REMOTE_SERVER)" \
		--device "$(REMOTE_DEVICE)" \
		--image "$(REMOTE_IMAGE)" \
		$(REMOTE_SERVER_ARGS)


# -----------------------------------------------------------------------------
# Inner build
# -----------------------------------------------------------------------------

else

DEPENDS := \
	$(OFILES:.o=.d)

$(OUTPUT).dol: $(OUTPUT).elf

$(OUTPUT).elf: $(OFILES)

-include $(DEPENDS)

endif
