#!/usr/bin/env python3

"""
Build GameCube Memory Card presentation data from carryhandle.cfg.

This is a build-time frontend only.

It reuses:
    ch_manifest.py     manifest parsing/validation
    ch_card_assets.py  CI8/RGB5A3 encoding

No manifest parsing or image conversion happens on the GameCube.
"""

from pathlib import Path

import argparse
import hashlib
import sys

from ch_manifest import (
    ManifestError,
    load_manifest,
)

from ch_card_assets import (
    CardAssetError,
    PRESENTATION_SIZE,
    build_presentation,
    write_if_changed,
)


def c_string(value):
    return (
        '"'
        + value
            .replace("\\\\", "\\\\\\\\")
            .replace('"', '\\\\"')
        + '"'
    )


def emit_header(card):
    filename = c_string(
        card["filename"]
    )

    sectors = card["sectors"]

    return f"""\
/*
 * GENERATED FILE.
 *
 * Generated by tools/ch_card_build.py.
 * Do not hand-edit.
 */

#ifndef CARRYHANDLE_GENERATED_CH_CARD_PRESENTATION_DATA_H
#define CARRYHANDLE_GENERATED_CH_CARD_PRESENTATION_DATA_H

#define CH_CARD_PRESENTATION_FILENAME \\
    {filename}

#define CH_CARD_FILE_SECTORS \\
    {sectors}u

#define CH_CARD_PRESENTATION_DATA_SIZE \\
    {PRESENTATION_SIZE}u

extern const unsigned char
    ch_card_presentation_data[
        CH_CARD_PRESENTATION_DATA_SIZE
    ];

#endif
"""


def emit_source(
    header_name,
    data,
):
    lines = []

    for offset in range(
        0,
        len(data),
        16,
    ):
        chunk = data[
            offset:offset + 16
        ]

        lines.append(
            "    "
            + ", ".join(
                f"0x{value:02x}"
                for value in chunk
            )
            + ","
        )

    body = "\n".join(lines)

    return f"""\
/*
 * GENERATED FILE.
 *
 * Generated by tools/ch_card_build.py.
 * Do not hand-edit.
 */

#include <carryhandle/ch_application_save.h>

#include "{header_name}"


const unsigned char
    ch_card_presentation_data[
        CH_CARD_PRESENTATION_DATA_SIZE
    ] =
{{
{body}
}};


static const CH_ApplicationSaveDescriptor
    applicationSaveDescriptor =
{{
    CH_CARD_PRESENTATION_FILENAME,
    CH_CARD_FILE_SECTORS,

    CH_APPLICATION_SAVE_PRESENTATION_OFFSET,

    ch_card_presentation_data,
    CH_CARD_PRESENTATION_DATA_SIZE
}};


const CH_ApplicationSaveDescriptor *
CH_ApplicationSaveGetDescriptor(void)
{{
    return
        &applicationSaveDescriptor;
}}
"""


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--manifest",
        required=True,
    )

    parser.add_argument(
        "--output-bin",
    )

    parser.add_argument(
        "--output-h",
        required=True,
    )

    parser.add_argument(
        "--output-c",
        required=True,
    )

    args = parser.parse_args()

    manifest_path = Path(
        args.manifest
    ).resolve()

    try:
        manifest = load_manifest(
            manifest_path
        )

        card = manifest[
            "memcard"
        ]

        if card is None:
            raise ManifestError(
                "manifest has no [memcard] section"
            )

        banner_path = (
            manifest_path.parent
            / card["banner"]
        )

        icon_path = (
            manifest_path.parent
            / card["icon"]
        )

        presentation = build_presentation(
            banner_path,
            icon_path,
            card["title"],
            card["comment"],
        )

    except (
        ManifestError,
        CardAssetError,
    ) as exc:
        print(
            f"CarryHandle CARD build error: {exc}",
            file=sys.stderr,
        )

        return 2

    data = presentation[
        "data"
    ]

    output_h = Path(
        args.output_h
    )

    output_c = Path(
        args.output_c
    )

    header_changed = write_if_changed(
        output_h,
        emit_header(card).encode("ascii"),
    )

    source_changed = write_if_changed(
        output_c,
        emit_source(
            output_h.name,
            data,
        ).encode("ascii"),
    )

    if args.output_bin:
        binary_changed = write_if_changed(
            args.output_bin,
            data,
        )
    else:
        binary_changed = False

    print(
        "CarryHandle CARD build generated"
    )

    print(
        f"  manifest     : {manifest_path}"
    )

    print(
        f"  filename     : {card['filename']}"
    )

    print(
        f"  sectors      : {card['sectors']}"
    )

    print(
        f"  title        : {card['title']}"
    )

    print(
        f"  comment      : {card['comment']}"
    )

    print(
        f"  banner       : {banner_path}"
    )

    print(
        f"  icon         : {icon_path}"
    )

    print(
        f"  presentation : {len(data)} bytes"
    )

    print(
        f"  sha256       : "
        f"{hashlib.sha256(data).hexdigest()}"
    )

    print(
        f"  header       : {output_h} "
        f"({'updated' if header_changed else 'unchanged'})"
    )

    print(
        f"  source       : {output_c} "
        f"({'updated' if source_changed else 'unchanged'})"
    )

    if args.output_bin:
        print(
            f"  binary       : {args.output_bin} "
            f"({'updated' if binary_changed else 'unchanged'})"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )
